- name: Run Redis container
  docker_container:
    name: "{{ redis_container_name }}"
    image: "{{ redis_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ redis_port }}:6379"