- name: Setup Docker Swarm with MySQL and Redis
  hosts: servers
  become: true
  gather_facts: yes

  roles:
    - { role: docker, tags: docker }
    - { role: swarm, tags: swarm }
    - { role: mysql, tags: mysql }
    - { role: redis, tags: redis }