- name: Run MySQL 8 container
  docker_container:
    name: "{{ mysql_container_name }}"
    image: "{{ mysql_image }}"
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    ports:
      - "{{ mysql_port }}:3306"